const http=require('http');
const fs=require('fs');
const path=require('path');
const WebSocket=require('ws');
const PORT=process.env.PORT||10000;
const rooms=new Map();
const QUESTIONS=[
 {title:'Pick the strongest role',badge:'1. ROLE',prompt:'You need help creating a professional business logo concept.',opts:['You are a professional brand designer.','You are a random internet user.','You are a calculator.','You are a game referee.'],ans:0},
 {title:'Set clear requirements',badge:'2. REQUIREMENTS',prompt:'You want a short social-media launch plan.',opts:['Give 5 actionable ideas with one example each.','Write as much as possible with no structure.','Only use difficult business jargon.','Do not provide any examples.'],ans:0},
 {title:'Add useful constraints',badge:'3. CONSTRAINTS',prompt:'You need the answer to be easy to use.',opts:['Use simple language and keep it under 300 words.','Make it 5,000 words and highly technical.','Use unexplained abbreviations.','Ignore the requested format.'],ans:0},
 {title:'Ask for a plan',badge:'4. PLAN',prompt:'Before executing a complex task, what should you request?',opts:['First outline a clear step-by-step plan, then execute.','Skip planning and guess the result.','Repeat the question several times.','Only give unrelated background information.'],ans:0},
 {title:'Build the complete prompt',badge:'⭐ FINAL CHALLENGE',prompt:'Which option combines the complete prompt anatomy?',opts:['Role + Requirements + Constraints + Plan.','Only a role.','Only a vague question.','Only a long list of emojis.'],ans:0}
];
function code(){let s='';const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';do{s='';for(let i=0;i<6;i++)s+=chars[Math.floor(Math.random()*chars.length)]}while(rooms.has(s));return s}
function send(ws,msg){if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(msg))}
function broadcast(room,msg){room.players.forEach(p=>send(p.ws,msg))}
function publicState(room){return {type:'state',players:room.players.map((p,i)=>({id:p.id,name:p.name,score:p.score,streak:p.streak,answered:!!p.answered,index:i})),round:room.round,total:QUESTIONS.length,question:QUESTIONS[room.round]&&{title:QUESTIONS[room.round].title,badge:QUESTIONS[room.round].badge,prompt:QUESTIONS[room.round].prompt,opts:QUESTIONS[room.round].opts},status:room.status}}
function maybeAdvance(room){if(room.players.length===2 && room.players.every(p=>p.answered)){setTimeout(()=>advance(room),900)}}
function advance(room){if(!rooms.has(room.code))return;if(room.round+1>=QUESTIONS.length){room.status='finished';broadcast(room,{type:'finished',players:room.players.map(p=>({name:p.name,score:p.score,streak:p.streak}))});return}room.round++;room.players.forEach(p=>p.answered=false);room.status='playing';broadcast(room,publicState(room))}
function cleanup(room){if(room.timer)clearTimeout(room.timer);rooms.delete(room.code)}
const server=http.createServer((req,res)=>{let p=req.url.split('?')[0];if(p==='/health'){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({ok:true,rooms:rooms.size}))}if(p==='/')p='/index.html';const file=path.join(__dirname,'public',p);fs.readFile(file,(e,data)=>{if(e){res.writeHead(404);return res.end('Not found')}const ext=path.extname(file);const ct=ext==='.html'?'text/html':ext==='.js'?'text/javascript':ext==='.css'?'text/css':'application/octet-stream';res.writeHead(200,{'content-type':ct});res.end(data)})});
const wss=new WebSocket.Server({server});
wss.on('connection',ws=>{let player=null;ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}if(m.type==='create'){const room={code:code(),players:[],round:0,status:'waiting'};player={id:Math.random().toString(36).slice(2),name:String(m.name||'Player 1').slice(0,20),score:0,streak:0,answered:false,ws};room.players.push(player);rooms.set(room.code,room);send(ws,{type:'created',code:room.code,playerId:player.id});send(ws,publicState(room));return}if(m.type==='join'){const room=rooms.get(String(m.code||'').toUpperCase());if(!room)return send(ws,{type:'error',message:'Room not found.'});if(room.players.length>=2)return send(ws,{type:'error',message:'Room is full.'});player={id:Math.random().toString(36).slice(2),name:String(m.name||'Player 2').slice(0,20),score:0,streak:0,answered:false,ws};room.players.push(player);room.status='playing';room.players.forEach(p=>p.answered=false);broadcast(room,publicState(room));return}if(!player)return;if(m.type==='answer'){const room=[...rooms.values()].find(r=>r.players.includes(player));if(!room||room.status!=='playing'||player.answered)return;const q=QUESTIONS[room.round];player.answered=true;const n=Number(m.answer);let correct=n===q.ans;if(correct){const pts=100+player.streak*25;player.score+=pts;player.streak++;send(ws,{type:'answerResult',correct,points:pts,answer:q.ans})}else{player.streak=0;send(ws,{type:'answerResult',correct,points:0,answer:q.ans})}broadcast(room,publicState(room));maybeAdvance(room)}});ws.on('close',()=>{if(!player)return;const room=[...rooms.values()].find(r=>r.players.includes(player));if(room){room.players=room.players.filter(p=>p!==player);if(room.players.length===0)cleanup(room);else{room.status='waiting';room.round=0;room.players[0].answered=false;send(room.players[0].ws,{type:'opponentLeft'});send(room.players[0].ws,publicState(room))}}})});
server.listen(PORT,'0.0.0.0',()=>console.log(`Prompt Master listening on ${PORT}`));
